@import gg.jte.Content
@param Content content

<!doctype html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1" />
    <title>Welcome page</title>
    <title>/users</title>
    <title>/</title>
</head>
<body>
<p>USERS:
</p>
${content}
<footer style="color: red; font-size: 10px;">
    <br>
    <hr>
    Урок Лейаут
</footer>
</body>
</html>